spring:
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
      routes:
        - id: auth-service
          uri: http://auth-service:5000
          predicates:
            - Path=/uaa/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: statistics-service
          uri: lb://statistics-service
          predicates:
            - Path=/statistics/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
      httpclient:
        connect-timeout: 20000
        response-timeout: 20s
    loadbalancer:
      enabled: true

  webflux:
    static-path-pattern: /**

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      defaultCircuitBreaker:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 20s

server:
  port: 4000
